apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ldg.name" . }}-env
  labels:
    {{- include "ldg.labels" . | nindent 4 }}
data:
  env.json: |
    {{- .Values.env | toJson | nindent 4 }}
  CSP_CONNECT_SRC: {{ .Values.nginx.cspConnectSrc | quote }}
