apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldg.name" . }}
  labels:
    {{- include "ldg.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "ldg.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
